#ifndef GLOBALS_H
#define GLOBALS_H

#define SCREEN_WIDTH		1280
#define SCREEN_HEIGHT		720
#define SCREEN_FPS			60

#define SCREEN_TICK_PER_FRAME (1000 / SCREEN_FPS)

#define MAP_X		100
#define MAP_Y		100
#define TILE_SIZE	32
#define BUTTON_SIZE	48

#define FIELD_X (MAP_X*TILE_SIZE)
#define FIELD_Y (MAP_Y*TILE_SIZE)

#define UI_X	256
#define UI_Y	SCREEN_HEIGHT
#define UI_PLACE_X	SCREEN_WIDTH - UI_X
#define UI_PLACE_Y	SCREEN_HEIGHT - UI_Y

//Tiles
#define TILE_NONE	{0, 0, 0, 0}
#define TILE_GRASS	{0, 0, TILE_SIZE, TILE_SIZE}
#define TILE_WATER	{32, 0, TILE_SIZE, TILE_SIZE}
#define TILE_SAND	{0, 32, TILE_SIZE, TILE_SIZE}
#define TILE_SHORE	{32, 32, TILE_SIZE, TILE_SIZE}
#define TILE_DIRT {0, 64, TILE_SIZE, TILE_SIZE}

#define BASE_GOLD			75
#define BASE_GOLD_STORAGE	100
#define BASE_STONE			25
#define BASE_STONE_STORAGE	50
#define BASE_POPULATION		0
#define BASE_POPULATION_MAX	5

//Rocks
#define ROCK_VALUE_MIN		30
#define ROCK_VALUE_MAX		50
#define GOLD_ROCK_VALUE_MIN	100
#define GOLD_ROCK_VALUE_MAX	150

#endif//GLOBALS_H 